"""
GRN Inference Task - Gene Regulatory Network Inference

Standalone multi-omics GRN inference task that infers regulatory networks directly from RNA and ATAC data.
Supports BEELINE benchmark (ChIP-seq ground truth) evaluation.
"""

from __future__ import annotations

import json
import logging
import os
from pathlib import Path
from typing import Any, Dict, List, Optional

import anndata as ad

from ..base_task import BaseTask, TaskConfig, TaskResult, ExecutionResult
from ...modules.data_parsing.semantic_parser import (
    SemanticDataParser, MultiOmicsSemanticParser,
)

logger = logging.getLogger(__name__)

# ChIP-seq ground truth default path
_DEFAULT_CHIPSEQ_GT = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "..", "..", "..",
    "data", "dataset", "chip_seq_TF",
)


class GRNInferenceTask(BaseTask):
    """
    Multi-omics GRN Inference Task

    Infers gene regulatory networks by integrating scRNA-seq and scATAC-seq data.
    Code is dynamically generated by LLM, with BEELINE benchmark evaluation support.
    """

    def __init__(self, config: Optional[TaskConfig] = None):
        if config is None:
            config = TaskConfig(task_type="grn")
        super().__init__(config)

        self.rna_path: Optional[str] = None
        self.atac_path: Optional[str] = None
        self.rna_adata: Optional[ad.AnnData] = None
        self.atac_adata: Optional[ad.AnnData] = None
        self.prior_network: Optional[Any] = None
        self.chipseq_ground_truth: Optional[str] = None
        self.last_beeline_metrics: Dict[str, Any] = {}

    def _parse_data(
        self,
        rna_path: Optional[str] = None,
        atac_path: Optional[str] = None,
        data_path: Optional[str] = None,
        rna_adata: Optional[ad.AnnData] = None,
        atac_adata: Optional[ad.AnnData] = None,
        data_name: Optional[str] = None,
        prior_network: Optional[Any] = None,
        chipseq_ground_truth: Optional[str] = None,
        **kwargs,
    ):
        self.prior_network = prior_network
        self.chipseq_ground_truth = chipseq_ground_truth

        if data_name is None:
            src = rna_path or atac_path or data_path
            if src:
                data_name = Path(src).stem
        self.data_name = data_name

        if data_path and not rna_path:
            rna_path = data_path

        self.rna_path = rna_path
        self.atac_path = atac_path
        self.rna_adata = rna_adata
        self.atac_adata = atac_adata

        has_multi = rna_path and atac_path

        if has_multi:
            parser = MultiOmicsSemanticParser(
                rna_path=rna_path,
                atac_path=atac_path,
                verbose=True,
                sample_n_obs=self.config.sample_n_obs,
                sample_n_vars=self.config.sample_n_vars,
            )
            self.data_info = parser.parse(include_sample=True)
            self.data_info['prompt_context'] = parser.get_prompt_context(include_sample=True)
        else:
            single_path = rna_path or data_path
            parser = SemanticDataParser(
                single_path, modality="rna", verbose=True,
                sample_n_obs=self.config.sample_n_obs,
                sample_n_vars=self.config.sample_n_vars,
            )
            self.data_info = parser.parse(include_sample=True)
            self.data_info['prompt_context'] = parser.get_prompt_context(include_sample=True)

        if self.prior_network is not None:
            self.data_info['prior_network'] = self.prior_network

        if self.chipseq_ground_truth is not None:
            self.data_info['chipseq_ground_truth'] = self.chipseq_ground_truth

        # Guide LLM to output the correct edge list format
        self.data_info['output_requirements'] = {
            'edge_list': {
                'format': 'CSV with columns: TF, Target, EdgeWeight',
                'save_path': 'outputs/grn_edge_list.csv',
                'description': 'TF-Target regulatory edge list with confidence/weight scores',
            }
        }

        if has_multi:
            if self.rna_adata is None and rna_path:
                self.rna_adata = ad.read_h5ad(rna_path)
            if self.atac_adata is None and atac_path:
                self.atac_adata = ad.read_h5ad(atac_path)
            self.executor.inject_multi_omics(
                rna_adata=self.rna_adata,
                atac_adata=self.atac_adata,
            )
        else:
            if self.rna_adata is None and (rna_path or data_path):
                self.rna_adata = ad.read_h5ad(rna_path or data_path)
            if self.rna_adata is not None:
                self.executor.inject_adata(self.rna_adata, var_name="adata")

        logger.info("GRN data parsed and injected")

    def _resolve_chipseq_path(self) -> Optional[str]:
        """Resolve the ChIP-seq ground truth directory path."""
        if self.chipseq_ground_truth:
            path = self.chipseq_ground_truth
        else:
            path = _DEFAULT_CHIPSEQ_GT

        if os.path.isdir(path):
            return path

        # Try resolving relative to the project root directory
        project_root = Path(__file__).resolve().parents[3]
        alt_path = project_root / path
        if alt_path.is_dir():
            return str(alt_path)

        logger.warning(f"ChIP-seq ground truth directory not found: {path}")
        return None

    def _evaluate_with_beeline(
        self,
        edge_list_path: str,
        round_num: int,
        top_k: float = 1.0,
        print_each_TF: bool = True,
        save_true_edges: bool = False,
        method: str = "Agent-GRN",
    ) -> Dict[str, Any]:
        """Evaluate GRN inference results using the BEELINE benchmark.

        Args:
            edge_list_path: Path to the inferred edge list CSV (TF, Target, EdgeWeight)
            round_num: Current round number
            top_k: Proportion of top edges to retain
            print_each_TF: Whether to print evaluation results for each TF
            save_true_edges: Whether to save ground truth edges
            method: Method name

        Returns:
            Dictionary of BEELINE evaluation metrics.
        """
        gt_path = self._resolve_chipseq_path()
        if gt_path is None:
            logger.warning("ChIP-seq ground truth path not available, skipping BEELINE evaluation")
            return {}

        try:
            import sys
            utils_dir = Path(__file__).resolve().parents[3] / "Utils"
            if str(utils_dir) not in sys.path:
                sys.path.insert(0, str(utils_dir))
            from benchmark_BEELINE import benchmark_expand
            import pandas as pd

            if not os.path.exists(edge_list_path):
                logger.warning(f"Edge list file not found: {edge_list_path}")
                return {}

            adj_df = pd.read_csv(edge_list_path)
            if not all(col in adj_df.columns for col in ["TF", "Target", "EdgeWeight"]):
                logger.warning("Edge list missing required columns (TF, Target, EdgeWeight)")
                return {}

            overall_df = benchmark_expand(
                adj_df,
                isFromFile=False,
                top_k=top_k,
                print_each_TF=print_each_TF,
                save_true_edges=save_true_edges,
                method=method,
                gt_path=gt_path,
            )

            metrics = {}
            for _, row in overall_df.iterrows():
                metric_name = row['Metric'].lower().replace('-', '').replace(' ', '_')
                metrics[f'beeline_{metric_name}_mean'] = float(row['Mean'])

            logger.info(f"[BEELINE] Round {round_num} evaluation: {metrics}")
            return metrics

        except Exception as e:
            logger.warning(f"BEELINE evaluation failed: {e}")
            return {}

    def _save_successful_code(
        self,
        generated_codes: List[str],
        execution_results: List[ExecutionResult],
        round_num: int = 1,
    ):
        super()._save_successful_code(generated_codes, execution_results, round_num)

        edge_list_path = "outputs/grn_edge_list.csv"
        if os.path.exists(edge_list_path):
            beeline_metrics = self._evaluate_with_beeline(edge_list_path, round_num)
            if beeline_metrics:
                self.last_beeline_metrics = beeline_metrics
                metrics_file = Path(self.config.output_dir) / f"grn_beeline_round{round_num}.json"
                metrics_file.parent.mkdir(parents=True, exist_ok=True)
                with open(metrics_file, 'w') as f:
                    json.dump(beeline_metrics, f, indent=2)
                logger.info(f"BEELINE metrics saved to {metrics_file}")


async def run_grn_inference(
    rna_path: Optional[str] = None,
    atac_path: Optional[str] = None,
    data_path: Optional[str] = None,
    prior_network: Optional[Any] = None,
    chipseq_ground_truth: Optional[str] = None,
    **kwargs,
) -> TaskResult:
    task = GRNInferenceTask()
    return await task.execute(
        rna_path=rna_path,
        atac_path=atac_path,
        data_path=data_path,
        prior_network=prior_network,
        chipseq_ground_truth=chipseq_ground_truth,
        **kwargs,
    )
