"""Perturbation Prediction Task - Cell Perturbation Prediction

Uses LLM to dynamically generate code.
"""
from __future__ import annotations
import logging
from pathlib import Path
from typing import Any, Dict, Optional
import anndata as ad
from ..base_task import BaseTask, TaskConfig, TaskResult
from ...modules.data_parsing.semantic_parser import SemanticDataParser
logger = logging.getLogger(__name__)

class PerturbationTask(BaseTask):
    """Perturbation prediction task - code is dynamically generated by LLM."""
    def __init__(self, config: Optional[TaskConfig] = None):
        if config is None:
            config = TaskConfig(task_type="perturbation")
        super().__init__(config)
        self.data_path: Optional[str] = None
        self.adata: Optional[ad.AnnData] = None
        self.mode: str = "drug"

    def _parse_data(self, data_path: Optional[str] = None,
                    adata: Optional[ad.AnnData] = None,
                    data_name: Optional[str] = None,
                    mode: str = "drug", **kwargs):
        self.data_path = data_path
        self.adata = adata
        self.mode = mode

        if data_name is None:
            src = data_path
            if src:
                data_name = Path(src).stem
        self.data_name = data_name

        # Set task_type based on mode to route to the correct LLM instruction
        if mode == "genetic":
            self.task_type = "genetic_perturbation"
        else:
            self.task_type = "perturbation"  # Default drug mode

        parser = SemanticDataParser(
            data_path or "", modality="rna", verbose=True,
            sample_n_obs=self.config.sample_n_obs,
            sample_n_vars=self.config.sample_n_vars
        )
        semantics = parser.parse(include_sample=True)
        self.data_info = semantics.to_dict()
        self.data_info['prompt_context'] = parser.get_prompt_context(include_sample=True)
        self.data_info['mode'] = mode

        # Extra context for genetic perturbation to help LLM understand data characteristics
        if mode == "genetic":
            self.data_info['perturbation_source'] = "gene perturbation (KO/KD/OE/CRISPR)"
            self.data_info['task_type'] = "genetic_perturbation"

        if self.adata is None and data_path:
            self.adata = ad.read_h5ad(data_path)
        self.executor.inject_adata(self.adata, var_name="adata")
        logger.info(f"Perturbation data parsed and injected (mode={mode})")
        logger.info("Code will be generated by LLM dynamically")

async def run_perturbation(data_path: Optional[str] = None, mode: str = "drug", **kwargs) -> TaskResult:
    task = PerturbationTask()
    return await task.execute(data_path=data_path, mode=mode, **kwargs)
