"""
Integration Task - Multi-omics Integration Task

Refactored from existing GRN/Multi_omics_integration.py
Uses LLM to dynamically generate code
"""

from __future__ import annotations

import logging
from typing import Any, Dict, List, Optional
from pathlib import Path

import numpy as np
import anndata as ad

from ..base_task import BaseTask, TaskConfig, TaskResult
from ...modules.execution.data_injection_executor import ExecutionResult
from ...modules.data_parsing.semantic_parser import MultiOmicsSemanticParser

logger = logging.getLogger(__name__)


class IntegrationTask(BaseTask):
    """
    Multi-omics integration task

    Integrate scRNA-seq and scATAC-seq data to learn shared latent representations
    Code is fully generated dynamically by LLM
    """

    def __init__(self, config: Optional[TaskConfig] = None):
        if config is None:
            config = TaskConfig(task_type="integration")
        super().__init__(config)

        self.rna_path: Optional[str] = None
        self.atac_path: Optional[str] = None
        self.rna_adata: Optional[ad.AnnData] = None
        self.atac_adata: Optional[ad.AnnData] = None
        self.last_output_path: Optional[str] = None
    
    def _parse_data(
        self,
        rna_path: Optional[str] = None,
        atac_path: Optional[str] = None,
        rna_adata: Optional[ad.AnnData] = None,
        atac_adata: Optional[ad.AnnData] = None,
        data_name: Optional[str] = None,
        **kwargs
    ):
        """Parse multi-omics data"""
        self.rna_path = rna_path
        self.atac_path = atac_path
        self.rna_adata = rna_adata
        self.atac_adata = atac_adata

        if data_name is None:
            parts = []
            if rna_path:
                parts.append(Path(rna_path).stem.replace("-RNA", "").replace("_RNA", ""))
            elif atac_path:
                parts.append(Path(atac_path).stem.replace("-ATAC", "").replace("_ATAC", ""))
            data_name = "_".join(parts) if parts else None
        self.data_name = data_name
        
        # Use semantic parser
        parser = MultiOmicsSemanticParser(
            rna_path=rna_path,
            atac_path=atac_path,
            verbose=True,
            sample_n_obs=self.config.sample_n_obs,
            sample_n_vars=self.config.sample_n_vars,
        )
        
        # Parse data semantics
        self.data_info = parser.parse(include_sample=True)
        
        # Get prompt context
        prompt_context = parser.get_prompt_context(include_sample=True)
        self.data_info['prompt_context'] = prompt_context
        
        # Inject data into executor
        if self.rna_adata is None and rna_path:
            self.rna_adata = ad.read_h5ad(rna_path)
        if self.atac_adata is None and atac_path:
            self.atac_adata = ad.read_h5ad(atac_path)
        
        self.executor.inject_multi_omics(
            rna_adata=self.rna_adata,
            atac_adata=self.atac_adata,
        )
        
        logger.info("Multi-omics data parsed and injected")
        logger.info("Code will be generated by LLM dynamically")

    async def execute(self, **kwargs) -> TaskResult:
        """Execute integration task and set output_path"""
        self.last_output_path = None
        result = await super().execute(**kwargs)
        result.output_path = self.last_output_path
        return result

    def _save_successful_code(
        self,
        generated_codes: List[str],
        execution_results: List[ExecutionResult],
        round_num: int = 1,
    ):
        """Save successful code and export integrated embedding h5ad file"""
        super()._save_successful_code(generated_codes, execution_results, round_num)

        # Extract embedding from successful execution results
        successful_results = [r for r in execution_results if r.success and not r.incomplete_reason]
        if not successful_results:
            return

        last_success = successful_results[-1]

        # Extract latent_representation from return_value or variables['result']
        latent = None
        metrics = {}

        rv = last_success.return_value
        if rv is None:
            rv = last_success.variables.get('result')

        if isinstance(rv, dict):
            latent = rv.get('latent_representation')
            metrics = rv.get('metrics', {})
            # Fallback: try other common keys
            if latent is None:
                for key in ('latent', 'embedding', 'z', 'X_latent'):
                    latent = rv.get(key)
                    if latent is not None:
                        break

        if latent is None:
            logger.warning("No latent_representation found in execution result, skipping h5ad export")
            return

        # Convert to numpy
        if hasattr(latent, 'cpu'):
            latent = latent.detach().cpu().numpy() if hasattr(latent, 'detach') else np.array(latent)
        elif not isinstance(latent, np.ndarray):
            latent = np.array(latent)

        latent = latent.astype(np.float32)

        # Build obs: merge RNA and ATAC cell metadata
        obs_parts = []
        modality_labels = []
        if self.rna_adata is not None:
            obs_parts.append(self.rna_adata.obs)
            modality_labels.extend(['RNA'] * self.rna_adata.n_obs)
        if self.atac_adata is not None:
            obs_parts.append(self.atac_adata.obs)
            modality_labels.extend(['ATAC'] * self.atac_adata.n_obs)

        if obs_parts:
            obs_df = ad.concat([ad.AnnData(obs=o) for o in obs_parts]).obs.copy()
            obs_df['modality'] = modality_labels
        else:
            n_cells = latent.shape[0]
            obs_df = ad.AnnData(np.empty((n_cells, 0))).obs
            obs_df['modality'] = 'unknown'

        # Align latent row count with obs row count
        n_cells = latent.shape[0]
        if len(obs_df) != n_cells:
            logger.warning(
                f"Latent rows ({n_cells}) != obs rows ({len(obs_df)}), "
                f"truncating obs to match latent"
            )
            obs_df = obs_df.iloc[:n_cells]

        # Build integrated AnnData
        integrated_adata = ad.AnnData(
            X=latent,
            obs=obs_df,
        )
        integrated_adata.obsm['X_integration'] = latent
        if metrics:
            import json as _json
            try:
                integrated_adata.uns['integration_metrics'] = {
                    k: float(v) if isinstance(v, (int, float)) else str(v)
                    for k, v in metrics.items()
                }
            except Exception:
                integrated_adata.uns['integration_metrics'] = _json.dumps(metrics, default=str)

        # Save h5ad
        output_dir = Path(self.config.output_dir) / "integrated"
        output_dir.mkdir(parents=True, exist_ok=True)

        data_name_part = f"{self.data_name}_" if self.data_name else ""
        h5ad_path = output_dir / f"{data_name_part}integration_round{round_num}.h5ad"
        integrated_adata.write_h5ad(str(h5ad_path))

        self.last_output_path = str(h5ad_path)
        logger.info(f"Integrated embedding saved to: {h5ad_path}")
        logger.info(f"  Shape: {integrated_adata.shape}, obsm keys: {list(integrated_adata.obsm.keys())}")


# Convenience function
async def run_integration(
    rna_path: Optional[str] = None,
    atac_path: Optional[str] = None,
    **kwargs
) -> TaskResult:
    """Convenience function: run multi-omics integration task"""
    task = IntegrationTask()
    return await task.execute(
        rna_path=rna_path,
        atac_path=atac_path,
        **kwargs
    )
